### ISSUE TITLE
Compile bug on Windows

### ISSUE THREAD

**Issue by Salingo** [DIYer22/bpycv#11]
Hello,
Thanks for providing this useful tool!

An error occured when I installing bpycv on Windows:
```
ERROR: Command errored out with exit status 1:
command: 'C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Salingo\\AppData\\Local\\Temp\\pip-install-o3rqu4a6\\bpycv\\setup.py'"'"'; __file__='"'"'C:\\Users\\Salingo\\AppData\\Local\\Temp\\pip-install-o3rqu4a6\\bpycv\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Salingo\AppData\Local\Temp\pip-pip-egg-info-nduuwed0'
        cwd: C:\Users\Salingo\AppData\Local\Temp\pip-install-o3rqu4a6\bpycv\
Complete output (5 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Users\Salingo\AppData\Local\Temp\pip-install-o3rqu4a6\bpycv\setup.py", line 13, in <module>
        long_description = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 318: illegal multibyte sequence
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I think this is a issue related to the string encoding, maybe you can try to modify line 12 in `setup.py` to:
`with open("README.md", encoding='utf-8') as f:`

Thanks!

**Comment by DIYer22** [comment]
Right now, I don't have a Windows enviroment to test this BUG. Could you fix bug and test, then creat a Pull Request to master branch?

**Comment by Salingo** [comment]
The bug is fixed and tested, thanks!
