### ISSUE TITLE
no module named 'cycler'

### ISSUE THREAD

**Issue by umyta** [DIYer22/bpycv#18]
Hi, I'm trying to run the demo script on ubuntu 18.04 with python3.7.7 and blender 2.92.0. However, during saving I get the following errors:

```
...
Saved: '/tmp/tmp3xramr2h.png'
 Time: 00:00.93 (Saving: 00:00.32)

.../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/boxx/ylcompat.py:69: BoxxWarning: warning from boxx
    os.environ["DISPLAY"] is not found
    plt.show() are redirect to plt.savefig(tmp)
    function: show, loga, crun, heatmap, plot will be affected
  def __setDisplayEnv():
Traceback (most recent call last):
  File ".../test_script.py", line 28, in <module>
    result = bpycv.render_data()
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/bpycv/render_utils.py", line 107, in render_data
    render_result["image"] = _render_image()
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/bpycv/render_utils.py", line 87, in render_image
    image = imread(png_path)[..., :3]
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/boxx/ylimg/ylimgTool.py", line 43, in imread
    beforImportPlt()
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/boxx/ylcompat.py", line 110, in beforImportPlt
    __noDisplayEnv()
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/boxx/ylcompat.py", line 85, in __noDisplayEnv
    import matplotlib.pyplot as plt
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File ".../blender-2.92.0-linux64/2.92/python/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 32, in <module>
    from cycler import Cycler, cycler as ccycler
ModuleNotFoundError: No module named 'cycler'
Blender quit
```
I have tried `./python3.7m -m pip install -U cycler`, and it shows `Requirement already satisfied`. Do you have any suggestions on how I can overcome this issue?

Thanks in advance.

**Comment by DIYer22** [comment]
I create a docker based on same enviroment with yours(ubuntu 18.04 with python3.7.7 and blender 2.92.0):  https://hub.docker.com/repository/docker/diyer22/bpycv
And everything works well. 
Sorroy, I don't know what happened to your enviroment.
