### ISSUE TITLE
bpycv.render_data error

### ISSUE THREAD

**Issue by liuyanqi** [DIYer22/bpycv#43]
There is an error with the random file name saved in /tmp/. Seems like the it was not able to generate the random filename.
I'm using blender 2.93 and python 3.9
```

Render image using: BLENDER_EEVEE
Saved: '/tmp/.png'
 Time: 00:00.18 (Saving: 00:00.00)

Traceback (most recent call last):
  File "/home/liuyanqi/spot/digit_new.blend/Text.002", line 225, in <module>
  File "/home/liuyanqi/spot/digit_new.blend/Text.002", line 144, in render_scene
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/bpycv/render_utils.py", line 110, in render_data
    render_result["image"] = _render_image()
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/bpycv/render_utils.py", line 90, in render_image
    image = imread(png_path)[..., :3]
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/boxx/ylimg/ylimgTool.py", line 46, in imread
    return imread(fname, as_grey, plugin, **plugin_args)
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/imageio/core/functions.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/imageio/core/imopen.py", line 137, in imopen
    request = Request(uri, io_mode)
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/imageio/core/request.py", line 245, in __init__
    self._parse_uri(uri)
  File "/home/liuyanqi/Downloads/blender-2.93.6-linux-x64/2.93/python/lib/python3.9/site-packages/imageio/core/request.py", line 383, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/tmp/tmp93g8ifud.png'
Error: Python script failed, check the message in the system console

```

**Comment by DIYer22** [comment]
Looks like ` withattr(render, "filepath", png_path)` in [render_image](https://github.com/DIYer22/bpycv/blob/d1f9fcb1327c455af8626638ba10af4ee919f04d/bpycv/render_utils.py#L84) dose not work, and image are saved to '/tmp/.png'

We have test `bpycv` on blender2.90, blender3.0 and blender3.1
You can try another blender version first.
